[package]
name = "tith"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
base64.workspace = true
tith-adapter = { path = "../tith-adapter" }
tith-bso = { path = "../tith-bso" }
tith-crypto.workspace = true
tith-ipc = { path = "../tith-ipc" }
tith-message-legacy = { path = "../tith-message-legacy" }
tith-ledger = { path = "../tith-ledger" }
tith-nodelist.workspace = true
tith-nodelist-legacy = { path = "../tith-nodelist-legacy" }
tith-submit = { path = "../tith-submit" }
tith-wire.workspace = true

[lints]
workspace = true
