[package]
name = "tith-submit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
tith-crypto.workspace = true
tith-ipc = { path = "../tith-ipc" }
tith-ipc-tcp.workspace = true
tith-wire.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[lints]
workspace = true
