[package]
name = "tith-exchange"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
tith-crypto = { path = "../tith-crypto" }
tith-wire = { path = "../tith-wire" }

[lints]
workspace = true

