[package]
name = "tith-bso"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
same-file.workspace = true
tith-message-legacy = { path = "../tith-message-legacy" }

[lints]
workspace = true
